### ISSUE TITLE
Rx/Tx LEDs for EPHY connector

### ISSUE THREAD

**Issue by hotteshen** [YuzukiHD/YuzukiChameleon#1]
Thanks for releasing another tremendous open-source design.

I am going to add the PoE power supply part to this board.
But I could not find a way to add Rx/Tx indicating LED.
Those pins were not in the "RJ45" connector, nor I could see them on the H616 datasheet.

How to add Rx/Tx LEDs?

![Screenshot from 2022-08-30 16-35-26](https://user-images.githubusercontent.com/58913889/187390111-827004d6-1194-4f62-9728-9c6c015ca4be.png)

**Comment by YuzukiTsuru** [comment]
h616 does not have a built-in PHY LED  interface. If you need to lead out the LED, you need to use an independent GPIO and configure the software

The main market of h616 is OTT. For this market place, the demand for RJ45 indicator light is not high, and two additional IO ports will be occupied if you want
