### ISSUE TITLE
 Ideas on changing HDMI to MIPI ports

### ISSUE THREAD

**Issue by thekidtonystark** [YuzukiHD/YuzukiChameleon#10]
I plan on using three of these within a VR headset, as a sort of multiplexer for 12 cameras maximum! Four will be connected to each board but some help turning the HDMI to MIPI would be great! Can't use a converter PCB as they are way too costly!

**Comment by YuzukiTsuru** [comment]
In fact, H616 is an incomplete chip version, which is designed for OTT special-purpose use. The actual complete chip is an industrial level chip called T507, The core, peripheral and register list are the same

![image](https://user-images.githubusercontent.com/12003087/195986969-e34bb477-9f72-48c4-8ac2-6c9dc975b804.png)

**Comment by thekidtonystark** [comment]
Thank you! Looks like I have some work to do on my end.
