### ISSUE TITLE
Bluetooth 5.0 support

### ISSUE THREAD

**Issue by dumtux** [YuzukiHD/YuzukiChameleon#14]
Hi Yuzuki,

For supporting Bluetooth 5.0, it looks like we can use AW859 or AW860.
* do you have any plan to update the design using this AW859/869 module?
* if not, can you point out some technical resources of AW859/869? I tried to find but it was difficult for me to find documentation in public like other Allwinner products.

**Comment by YuzukiTsuru** [comment]
I'm sorry that there is no updated plan for this project at present, but I can provide several data manuals for reference
[AW869A_SPEC_V1.3.pdf](https://github.com/YuzukiHD/YuzukiChameleon/files/10137364/AW869A_SPEC_V1.3.pdf)

and in my other project:
![image](https://user-images.githubusercontent.com/12003087/205194256-6e0f9806-1b94-4e4f-9db5-b637ab5c0fe1.png)

AW869 IO is 1.8v

**Comment by dumtux** [comment]
Thank you.
