### ISSUE TITLE
no video encoder library in tinalinux image

### ISSUE THREAD

**Issue by nihui** [YuzukiHD/YuzukiChameleon#20]
`/usr/lib/libvencoder.so` is missing though there is `/usr/lib/libvdecoder.so` for video decoder

**Comment by chainsx** [comment]
![tietie](https://github.com/YuzukiHD/YuzukiChameleon/assets/26809264/41436cfd-e013-401f-8454-e9869da7c944)

**Comment by chainsx** [comment]
https://github.com/YuzukiHD/YuzukiChameleon/releases/download/0.0.1/tina_h616-yuzukichameleon_uart0.zip
