### ISSUE TITLE
H616_YuzukiChameleon_3.0.0_debian_bullseye_server_linux5.16.17.img Can‘t Open in PhoenixSuit

### ISSUE THREAD

**Issue by 8023** [YuzukiHD/YuzukiChameleon#21]
![image](https://github.com/YuzukiHD/YuzukiChameleon/assets/5680998/a14e3837-47b6-4b98-a4ff-61639067704f)
使用PhoenixSuit无法打开release-0.0.2中的img文件。文件经多次下载校验确认无误。

**Comment by lava081** [comment]
I met the same problem. How did you solve it?
