### ISSUE TITLE
Oshwhub

### ISSUE THREAD

**Issue by dogukansahil** [YuzukiHD/YuzukiChameleon#22]
Oshwhub link is not working. Do you still have the opportunity to share the datasheet?

**Comment by YuzukiTsuru** [comment]
https://github.com/YuzukiHD/YuzukiChameleon/tree/master/Datasheet

**Comment by dogukansahil** [comment]
Unfortunately, jlcpcb does not have a processor, I will have to make many changes. But thank you for sharing the project.
