### ISSUE TITLE
BOM Generating Issue for Reset Circuit Resistor

### ISSUE THREAD

**Issue by hotteshen** [YuzukiHD/YuzukiChameleon#3]
While purchasing parts for PCBA, I faced another issue.
The resistor R28 is noted as 510ohm, but the part number was for 10kohm.
Which one is correct?

![Screenshot from 2022-09-14 11-54-48](https://user-images.githubusercontent.com/58913889/190056069-463a7164-8833-47d1-b4f9-ea36ad69ad6a.png)
![Screenshot from 2022-09-14 11-56-40](https://user-images.githubusercontent.com/58913889/190056130-3f0400b2-1b48-4730-8225-ce438d314214.png)

**Comment by YuzukiTsuru** [comment]
510ohm, Don't use the BOM generated by EDA, use the sorted BOM provided in this repo

**Comment by hotteshen** [comment]
Ok, thanks.
