### ISSUE TITLE
easyeda can't

### ISSUE THREAD

**Issue by frayray909090** [YuzukiHD/YuzukiChameleon#4]
how do i open it in easyeda

**Comment by YuzukiTsuru** [comment]
maybe you need easyeda pro

**Comment by hotteshen** [comment]
> how do i open it in easyeda

Go to https://pro.easyeda.com/editor and import the project files.

**Comment by frayray909090** [comment]
it still wont work
it says the file formate is wrong im putting all the stuff in so just the zip you get off of the github download button

**Comment by dumtux** [comment]
If you download this GitHub repository using **Download button**, it means you zipped the whole project.
This project itself is not an EasyEDA project.
Instead, this is a meta-project including all about hardware design and documentation.
1. clone this repository to your local storage
2. navigate to `[YuzukiChameleon)/Hardware/EDAProject/`
3. you can see a zip file, import it from EasyEDA Pro (not standard)
