### ISSUE TITLE
BOM: Some Resistors Are Not Listed in BOM

### ISSUE THREAD

**Issue by hotteshen** [YuzukiHD/YuzukiChameleon#5]
![Screenshot from 2022-09-22 19-35-21](https://user-images.githubusercontent.com/58913889/191736382-df21af4b-6743-4f23-bbe1-16d1258385bf.png)

On the schematic, the R26 is a 6.04k resistor.
But it was not listed in the revised [BOM_Board1_PCB1_2022-08-28.xlsx](https://github.com/YuzukiHD/YuzukiChameleon/blob/master/Hardware/BOM%26PickAndPlace/BOM_Board1_PCB1_2022-08-28.xlsx) sheet.

![Screenshot from 2022-09-22 19-30-51](https://user-images.githubusercontent.com/58913889/191735717-f0e2be1d-1a61-4a18-9e80-dab7fd5fe2fc.png)

The similar cases for 240ohm resistors R6, R8, and R9 for SZQ/ZQ pins of the DRAM circuit.

R6, R8, R9, and R26 are not present in BOM - does it mean not to assemble?

And what does that resistor R26 do on the `EPHY_RTX` pin?

**Comment by YuzukiTsuru** [comment]
I updated the BOM, I may have accidentally deleted the information of these two resistors when I was sorting it out, sorry for that

**Comment by YuzukiTsuru** [comment]
The resistance of the network PHY seems a matching resistance. In my test, it seems that the change of the resistance value will affect the network speed. It is best not to modify it.

**Comment by hotteshen** [comment]
Thank you for your quick reply.
The board assembly is almost finished.
I'll test networking speed when I get the board a couple of days later.
And if I encounter a problem with networking speed, I'll add more comments below.

**Comment by YuzukiTsuru** [comment]
Note that the network interface requires an external 100M network Magnetic Modules

**Comment by hotteshen** [comment]
![Screenshot from 2022-09-23 14-18-46](https://user-images.githubusercontent.com/58913889/191902233-fb69f300-8bbb-4378-a0ca-6e48f5a9400d.png)

Yes, I used PoE RJ45 jack with integrated 1:1 transformer.
